name: Pack Nuget
on:
  release:
    types: [published]
jobs:
  publish:
    name: Pack and Publish
    runs-on: windows-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Nuget.exe
        uses: NuGet/setup-nuget@v1.2.0
        with:
          nuget-api-key: ${{secret.NUGET_TOKEN}}

      - run: nuget restore MyProject.sln
