name: Pack Nuget
on:
  release:
    types: [published]
jobs:
  publish:
    name: Pack and Publish
    runs-on: windows-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create Build Directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget restore TiaGenerator.Tia.sln

      - name: Build Solution
        run: |
          msbuild.exe TiaGenerator.Tia.sln /nologo /nr:false /p:DeployOnBuild=true /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: TiaGenerator.TiaBundle
          path: "./_build"    
      
      - name: Setup Nuget.exe
        uses: NuGet/setup-nuget@v1.2.0

      - run: nuget pack -Version ${{ github.event.release.tag_name }} -Properties "Configuration=Release;PackageReleaseNotes=See https://github.com/janbiehl/TiaGenerator.Tia/releases/tag/${{ github.event.release.tag_name }}"
#      - run: nuget pack package.nuspec -p "Configuration=Release;Version=${{ github.event.release.tag_name }};PackageReleaseNotes=See https://github.com/janbiehl/TiaGenerator.Tia/releases/tag/${{ github.event.release.tag_name }}"
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.nupkg
      
      - run: nuget setApiKey ${{secrets.NUGET_TOKEN}}
      
      - run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json
